export default [{
  keyword: [
    "abstract",
    "boolean",
    "byte",
    "char",
    "class",
    "const",
    "debugger",
    "default",
    "delete",
    "double",
    "enum",
    "export",
    "extends",
    "false",
    "final",
    "float",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "super",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "volatile",
    "with"
  ],
  discription: '声明变量，条件语句',
  color: '#569cd6'
}, {
  keyword: ['break', 'case', 'catch', 'continue', 'do', 'else', 'goto', 'if', 'finally', 'switch', 'while'],
  discription: '条件语句',
  color: '#c586c0'
}, {
  keyword: ['Math', 'console', 'this', 'document', 'window', 'arguments', 'null', 'undefined', 'Object', 'String', 'Number', 'Array', 'Promise', 'Set', 'Map', 'WeakSet', 'WeakMap', 'prototype', 'Error'],
  discription: '内置对象',
  color: '#9cdcfe'
}, {
  keyword: ['random', 'pow', 'round', 'floor', 'log', 'replace', 'from', 'map', 'forEach', 'parseInt', 'push', 'unshift', 'shift', 'pull', 'toString', 'slice', 'remove', 'append', 'prepend'],
  discription: '注册方法',
  color: '#dcdcaa'
},]
